// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: device/device_info.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceInfoMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	OrgUuid  string `protobuf:"bytes,2,opt,name=org_uuid,json=orgUuid,proto3" json:"org_uuid,omitempty"`
	Serial   string `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
}

func (x *DeviceInfoMessage) Reset() {
	*x = DeviceInfoMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_device_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoMessage) ProtoMessage() {}

func (x *DeviceInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_device_device_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoMessage.ProtoReflect.Descriptor instead.
func (*DeviceInfoMessage) Descriptor() ([]byte, []int) {
	return file_device_device_info_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfoMessage) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInfoMessage) GetOrgUuid() string {
	if x != nil {
		return x.OrgUuid
	}
	return ""
}

func (x *DeviceInfoMessage) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

var File_device_device_info_proto protoreflect.FileDescriptor

var file_device_device_info_proto_rawDesc = []byte{
	0x0a, 0x18, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x22, 0x63, 0x0a, 0x11, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x67, 0x5f, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x67, 0x55, 0x75, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x42, 0x0f, 0x5a, 0x0d, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_device_device_info_proto_rawDescOnce sync.Once
	file_device_device_info_proto_rawDescData = file_device_device_info_proto_rawDesc
)

func file_device_device_info_proto_rawDescGZIP() []byte {
	file_device_device_info_proto_rawDescOnce.Do(func() {
		file_device_device_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_device_device_info_proto_rawDescData)
	})
	return file_device_device_info_proto_rawDescData
}

var file_device_device_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_device_device_info_proto_goTypes = []interface{}{
	(*DeviceInfoMessage)(nil), // 0: models.DeviceInfoMessage
}
var file_device_device_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_device_device_info_proto_init() }
func file_device_device_info_proto_init() {
	if File_device_device_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_device_device_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceInfoMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_device_device_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_device_device_info_proto_goTypes,
		DependencyIndexes: file_device_device_info_proto_depIdxs,
		MessageInfos:      file_device_device_info_proto_msgTypes,
	}.Build()
	File_device_device_info_proto = out.File
	file_device_device_info_proto_rawDesc = nil
	file_device_device_info_proto_goTypes = nil
	file_device_device_info_proto_depIdxs = nil
}
