// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: device/receipt.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReceiptDetailMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName   string             `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	DeviceInfo *DeviceInfoMessage `protobuf:"bytes,2,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
}

func (x *ReceiptDetailMessage) Reset() {
	*x = ReceiptDetailMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_receipt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiptDetailMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptDetailMessage) ProtoMessage() {}

func (x *ReceiptDetailMessage) ProtoReflect() protoreflect.Message {
	mi := &file_device_receipt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptDetailMessage.ProtoReflect.Descriptor instead.
func (*ReceiptDetailMessage) Descriptor() ([]byte, []int) {
	return file_device_receipt_proto_rawDescGZIP(), []int{0}
}

func (x *ReceiptDetailMessage) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ReceiptDetailMessage) GetDeviceInfo() *DeviceInfoMessage {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

var File_device_receipt_proto protoreflect.FileDescriptor

var file_device_receipt_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x1a, 0x18,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x14, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x70, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3a, 0x0a,
	0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0a, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x0f, 0x5a, 0x0d, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_device_receipt_proto_rawDescOnce sync.Once
	file_device_receipt_proto_rawDescData = file_device_receipt_proto_rawDesc
)

func file_device_receipt_proto_rawDescGZIP() []byte {
	file_device_receipt_proto_rawDescOnce.Do(func() {
		file_device_receipt_proto_rawDescData = protoimpl.X.CompressGZIP(file_device_receipt_proto_rawDescData)
	})
	return file_device_receipt_proto_rawDescData
}

var file_device_receipt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_device_receipt_proto_goTypes = []interface{}{
	(*ReceiptDetailMessage)(nil), // 0: models.ReceiptDetailMessage
	(*DeviceInfoMessage)(nil),    // 1: models.DeviceInfoMessage
}
var file_device_receipt_proto_depIdxs = []int32{
	1, // 0: models.ReceiptDetailMessage.device_info:type_name -> models.DeviceInfoMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_device_receipt_proto_init() }
func file_device_receipt_proto_init() {
	if File_device_receipt_proto != nil {
		return
	}
	file_device_device_info_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_device_receipt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiptDetailMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_device_receipt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_device_receipt_proto_goTypes,
		DependencyIndexes: file_device_receipt_proto_depIdxs,
		MessageInfos:      file_device_receipt_proto_msgTypes,
	}.Build()
	File_device_receipt_proto = out.File
	file_device_receipt_proto_rawDesc = nil
	file_device_receipt_proto_goTypes = nil
	file_device_receipt_proto_depIdxs = nil
}
